name: tool_base
description: Base for developing command line apps. Take from Flutter Tools.
version: 2.0.0
homepage: https://github.com/mmcc007/tool_base
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: ^3.1.2
  file: ^7.0.0
  intl: ^0.19.0
  platform: ^3.0.0-nullsafety.2
  process: ^5.0.2
  pub_cache: ^0.3.1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.1
  test: ^1.16.0-nullsafety.5
  mockito: ^5.4.4
  quiver: ^3.2.1
  file_testing: ^3.0.0
